services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-taller
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
  phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin-taller
        environment:
            PMA_HOST: mariadb
            PMA_USER: root
            PMA_PASSWORD: rootpassword
        ports:
        - "8080:80"
  database:
    image: mongo:latest
    container_name: ${DATABASE_HOST}
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${DATABASE_PORT}:27017"
    volumes:
      - database-v:/data/db
volumes:
  database-v:
    name: "database-v"
