module.exports = {
  DATABASE_HOST: process.env.DATABASE_HOST,
  DATABASE_PORT: process.env.DATABASE_PORT,
  DATABASE_COLLECTION: process.env.DATABASE_COLLECTION,
  DATABASE_USERNAME: process.env.MONGO_INITDB_ROOT_USERNAME,
  DATABASE_PASSWORD: process.env.MONGO_INITDB_ROOT_PASSWORD,
  DATABASE_DB: process.env.MONGO_INITDB_DATABASE,
  SERVER_HOST: process.env.SERVER_HOST,
  SERVER_PORT: process.env.SERVER_PORT,
};
